name: On Deploy gh-pages
on:
  deployment_status

jobs:
  purge-cache:
    name: 'Purge Cloudflare Cache'
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Output Debug Info
        run: |
          echo "Environment: ${{ github.event.deployment_status.environment }}"
      - name: 'Purge Cloudflare Cache'
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_WZ2100_ZONE }}
          CLOUDFLARE_CACHEPURGE_TOKEN: ${{ secrets.CLOUDFLARE_WZ2100_CACHEPURGE_TOKEN }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache" \
               -H "Authorization: Bearer ${CLOUDFLARE_CACHEPURGE_TOKEN}" \
               -H "Content-Type: application/json" \
               --data '{"purge_everything":true}'
